### ISSUE TITLE
Upstart Week 2a TODO

### ISSUE THREAD

**Issue by vicky-sunshine** [Kiwi-Learn/kiwi-scraper#10]
assignment:
https://docs.google.com/document/d/1opE-jLMAtMHK_WoQ8SAtDwuTDcE5EeYGFE38KEFbV48/edit#heading=h.ud3r69sbbpf1

summary:
- [x] rake
- [x] travis ci integration
- [x] web playback stubbing with vcr
- [x] publish gem
- [x] update readme.md
- [x] submit our gem name (kiwicourse) to canvus
